'use client';

import { useState, useEffect } from 'react';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import { 
  BookOpen, 
  Award, 
  Users, 
  Heart,
  Microscope,
  Globe,
  Mail,
  Phone,
  Calendar,
  TrendingUp,
  Leaf,
  Star,
  Quote,
  MapPin,
  Target,
  Lightbulb,
  Handshake,
  ArrowRight,
  Play,
  Download,
  MessageCircle,
  Tv,
  Newspaper,
  Radio,
  ExternalLink,
  Flag,
  Trophy,
  Shield,
  Flower,
  Home,
  Landmark,
  CheckCircle,
  Briefcase,
  Zap
} from 'lucide-react';

const milestones = [
  {
    year: '1998',
    title: 'The Health Crisis Discovery',
    description: 'Peter Singh and Neeno Kaur faced severe respiratory issues in Delhi, sparking their journey into sustainable agriculture.',
    impact: 'Personal health transformation',
    icon: Heart
  },
  {
    year: '2005',
    title: 'Academic Foundation',
    description: 'Dr. Peter Singh completed his PhD in Agricultural Sciences, specializing in sustainable farming techniques.',
    impact: 'Scientific credibility established',
    icon: BookOpen
  },
  {
    year: '2010',
    title: 'First Breakthrough',
    description: 'Successfully implemented aquaponics system achieving 60% air quality improvement in their home.',
    impact: '60% AQI improvement achieved',
    icon: Lightbulb
  },
  {
    year: '2015',
    title: 'Community Impact Begins',
    description: 'Started training local farmers and families, documenting systematic improvements in health and income.',
    impact: '50+ families transformed',
    icon: Users
  },
  {
    year: '2020',
    title: 'Research Recognition',
    description: 'Published groundbreaking research on urban aquaponics and received government recognition.',
    impact: '12 peer-reviewed papers published',
    icon: Award
  },
  {
    year: '2024',
    title: 'Academy Launch',
    description: 'Launched comprehensive education platform, scaling impact to 750+ successful graduates.',
    impact: '750+ lives transformed',
    icon: Globe
  }
];

const achievements = [
  {
    metric: '750+',
    label: 'Successful Graduates',
    description: 'Families now breathing clean air',
    icon: Users,
    color: 'blue'
  },
  {
    metric: '94.6%',
    label: 'Average AQI Improvement',
    description: 'Consistent across all implementations',
    icon: TrendingUp,
    color: 'green'
  },
  {
    metric: '₹18.5K',
    label: 'Average Monthly Income',
    description: 'Generated by graduates',
    icon: Target,
    color: 'purple'
  },
  {
    metric: '26 Years',
    label: 'Research Experience',
    description: 'Dedicated to sustainable agriculture',
    icon: Microscope,
    color: 'orange'
  }
];

const testimonials = [
  {
    name: 'Dr. Rajesh Mehta',
    role: 'Agricultural Scientist, ICAR',
    quote: 'Dr. Peter Singh\'s work represents a paradigm shift in urban agriculture. His systematic approach to combining air quality improvement with income generation is revolutionary.',
    image: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=400'
  },
  {
    name: 'Priya Sharma',
    role: 'Trained Farmer, Delhi',
    quote: 'Neeno Kaur\'s personal journey inspired me to transform my own health. The organic farming techniques she taught have changed my family\'s life completely.',
    image: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400'
  },
  {
    name: 'Prof. Anita Gupta',
    role: 'Environmental Science, DU',
    quote: 'Their research methodology is impeccable. The combination of scientific rigor with practical application makes their work truly impactful.',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400'
  }
];

const mediaCoverage = {
  international: [
    {
      outlet: 'The Week Magazine',
      country: 'India',
      type: 'Print',
      headline: 'Revolutionary Approach to Delhi\'s Air Pollution Crisis',
      description: 'In-depth feature on Dr. Singh\'s aquaponics methodology and its impact on urban air quality.',
      date: '2023',
      icon: Newspaper,
      link: '#'
    },
    {
      outlet: 'CNN-News18',
      country: 'India',
      type: 'Television',
      headline: 'Scientist\'s Personal Journey Becomes Public Solution',
      description: 'Prime-time documentary featuring the transformation from health crisis to community impact.',
      date: '2023',
      icon: Tv,
      link: '#'
    },
    {
      outlet: 'NDTV',
      country: 'India',
      type: 'Television',
      headline: 'Aquaponics: The Future of Urban Air Purification',
      description: 'Special report on sustainable solutions for India\'s pollution challenges.',
      date: '2024',
      icon: Tv,
      link: '#'
    },
    {
      outlet: 'The Better India',
      country: 'India',
      type: 'Digital',
      headline: 'From Crisis to Solution: A Delhi Family\'s Air Quality Revolution',
      description: 'Comprehensive story of personal transformation and community impact.',
      date: '2023',
      icon: Globe,
      link: '#'
    },
    {
      outlet: 'Times of India',
      country: 'India',
      type: 'Print',
      headline: 'Urban Farming Pioneer Transforms Delhi Air Quality',
      description: 'Feature article on innovative approaches to urban environmental challenges.',
      date: '2024',
      icon: Newspaper,
      link: '#'
    },
    {
      outlet: 'Indian Express',
      country: 'India',
      type: 'Print',
      headline: 'Breathing Easy: The Science Behind Clean Air at Home',
      description: 'Technical analysis of aquaponics systems and their environmental benefits.',
      date: '2024',
      icon: Newspaper,
      link: '#'
    },
    {
      outlet: 'German TV (Weltspiegel)',
      country: 'Germany',
      type: 'Television',
      headline: 'Indian Innovation: Fighting Air Pollution with Agriculture',
      description: 'International documentary showcasing Indian solutions to global environmental challenges.',
      date: '2023',
      icon: Tv,
      link: '#'
    },
    {
      outlet: 'Telegraph London',
      country: 'United Kingdom',
      type: 'Print',
      headline: 'Delhi Scientist\'s Green Revolution Against Pollution',
      description: 'International coverage of innovative environmental solutions from India.',
      date: '2024',
      icon: Newspaper,
      link: '#'
    },
    {
      outlet: 'NHK World Japan',
      country: 'Japan',
      type: 'Television',
      headline: 'Sustainable Solutions: India\'s Air Quality Innovation',
      description: 'Global broadcast featuring sustainable technology and environmental innovation.',
      date: '2024',
      icon: Tv,
      link: '#'
    }
  ]
};

const governmentRecognition = [
  {
    year: '1988',
    title: 'Punjab Government Award for Beekeeping Industry Development',
    authority: 'Government of Punjab',
    description: 'Recognition for pioneering work in sustainable beekeeping practices and industry development.',
    icon: Trophy,
    color: 'yellow'
  },
  {
    year: '1998',
    title: 'Excellence Award for Honey Production Increase',
    authority: 'Ministry of Agriculture',
    description: 'Awarded for significant contributions to increasing honey production through innovative techniques.',
    icon: Award,
    color: 'orange'
  },
  {
    year: '2000',
    title: 'Founding Member, National Beekeeping Development Board',
    authority: 'Government of India',
    description: 'Appointed as founding member for establishing national beekeeping standards and policies.',
    icon: Shield,
    color: 'blue'
  },
  {
    year: '2010',
    title: 'Resource Person, Ministry of Agriculture',
    authority: 'Government of India',
    description: 'Designated as expert resource person for sustainable agriculture and environmental initiatives.',
    icon: Flag,
    color: 'green'
  }
];

const mediaQuotes = [
  {
    quote: "Dr. Singh's methodology represents a breakthrough in urban environmental management, combining scientific rigor with practical application.",
    source: "The Week Magazine",
    journalist: "Environmental Correspondent"
  },
  {
    quote: "What started as a family's health crisis has evolved into a scalable solution for one of India's most pressing environmental challenges.",
    source: "CNN-News18",
    journalist: "Prime Time Documentary"
  },
  {
    quote: "The international community is taking notice of this innovative approach to air quality management emerging from Delhi.",
    source: "Telegraph London",
    journalist: "International Affairs Desk"
  }
];

const familyLegacy = {
  peter: {
    name: "Peter Singh",
    birthYear: 1945,
    birthPlace: "Punjab Organic Farm",
    education: [
      "Lawrence School Sanawar",
      "St. Stephens College Delhi (Mathematics Honours)"
    ],
    career: [
      "Chose farming over academia in 1973 - \"The land called me back\"",
      "Pioneer: First Apis Mellifera beekeeping in Punjab (500 colonies, 80kg honey each)",
      "Export Success: 2000 tons honey annually to Germany & USA",
      "Community Impact: Trained 750 farmers in sustainable practices"
    ],
    recognition: [
      "1988 Punjab Government Award for Beekeeping",
      "1998 Excellence Award for honey production increase"
    ],
    currentRole: "Technical systems designer and aquaponics innovator",
    image: "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=600"
  },
  neeno: {
    name: "Sarparveen (Neeno) Kaur",
    birthYear: 1955,
    achievements: [
      "All India President, FICCI Ladies Organization (1997-1998)",
      "Health Transformation: Overcame Chronic Lymphocytic Leukemia (1998-2009) through organic lifestyle",
      "Expertise: Plant cultivation, permaculture systems, organic garden management",
      "Achievements: 3x consecutive First Prize winner - Goa Organic Garden Competition"
    ],
    currentRole: "Manages all plant growing operations and course curriculum",
    image: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=600"
  },
  nextGen: [
    {
      name: "Kirat Singh",
      relation: "Son",
      education: "Harvard University graduate",
      role: "Software entrepreneur, manages Goa operations",
      image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
      name: "Jyotsna Kaur",
      relation: "Daughter",
      education: "MBA graduate",
      role: "Social entrepreneur, Lucknow home implementation",
      image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600"
    }
  ],
  familyPhoto: "https://images.pexels.com/photos/3807737/pexels-photo-3807737.jpeg?auto=compress&cs=tinysrgb&w=800"
};

export default function AboutPage() {
  const [mounted, setMounted] = useState(false);
  const [activeTimeline, setActiveTimeline] = useState(0);

  useEffect(() => {
    setMounted(true);
    
    // Auto-advance timeline
    const interval = setInterval(() => {
      setActiveTimeline(prev => (prev + 1) % milestones.length);
    }, 4000);

    return () => clearInterval(interval);
  }, []);

  if (!mounted) {
    return null;
  }

  const getColorClasses = (color: string) => {
    const colors = {
      blue: 'text-blue-600 bg-blue-50 border-blue-200',
      green: 'text-green-600 bg-green-50 border-green-200',
      purple: 'text-purple-600 bg-purple-50 border-purple-200',
      orange: 'text-orange-600 bg-orange-50 border-orange-200',
      yellow: 'text-yellow-600 bg-yellow-50 border-yellow-200'
    };
    return colors[color as keyof typeof colors] || colors.blue;
  };

  const getMediaIcon = (type: string) => {
    switch (type) {
      case 'Television':
        return Tv;
      case 'Print':
        return Newspaper;
      case 'Digital':
        return Globe;
      case 'Radio':
        return Radio;
      default:
        return Newspaper;
    }
  };

  return (
    <main className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      <Header />
      
      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-br from-green-50 via-blue-50 to-white">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <Badge variant="outline" className="mb-4 px-4 py-2 text-green-700 border-green-200">
                <Heart className="w-4 h-4 mr-2" />
                Our Story
              </Badge>
              <h1 className="text-4xl md:text-6xl font-bold mb-6 text-gray-900">
                Pioneering{' '}
                <span className="text-green-700">Sustainable Agriculture</span>
              </h1>
              <p className="text-xl text-gray-600 mb-8 leading-relaxed max-w-4xl mx-auto">
                From a personal health crisis to a revolutionary movement transforming lives across India. 
                Meet the visionary leaders who turned desperation into hope, science into solution, 
                and individual transformation into community impact.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button size="lg" className="bg-green-700 hover:bg-green-800">
                  <Play className="w-5 h-5 mr-2" />
                  Watch Our Story
                </Button>
                <Button variant="outline" size="lg">
                  <Download className="w-5 h-5 mr-2" />
                  Download Impact Report
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Welcome Section */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <Card className="p-8 bg-gradient-to-r from-green-50 to-blue-50 border-green-200">
              <CardContent className="p-0">
                <div className="text-center mb-8">
                  <Leaf className="w-12 h-12 text-green-600 mx-auto mb-4" />
                  <h2 className="text-3xl font-bold text-gray-900 mb-4">
                    Welcome to Aanant Aquaponics Academy
                  </h2>
                </div>
                <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed">
                  <p className="mb-6">
                    At Aanant Aquaponics Academy, we believe that sustainable agriculture is not just about growing food—it's about 
                    cultivating hope, health, and prosperity for communities worldwide. Our commitment to organic farming practices 
                    and innovative aquaponics systems stems from a deeply personal journey that began with a health crisis and 
                    evolved into a mission to transform lives.
                  </p>
                  <p className="mb-6">
                    Founded by Dr. Peter Singh and Neeno Kaur, our academy represents 26 years of dedicated research, experimentation, 
                    and real-world application. We've witnessed firsthand how sustainable agriculture can dramatically improve air quality, 
                    generate substantial income, and create thriving ecosystems that benefit both people and the planet.
                  </p>
                  <p>
                    Today, we're proud to have trained over 750 families who have successfully implemented our methods, achieving 
                    an average of 94.6% improvement in their home air quality while generating sustainable monthly incomes. 
                    Our approach combines cutting-edge science with time-tested organic principles, creating solutions that are 
                    both environmentally responsible and economically viable.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* The Aanant Family Legacy Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <Badge variant="outline" className="mb-4 px-4 py-2 text-amber-700 border-amber-200">
                <Landmark className="w-4 h-4 mr-2" />
                Family Legacy
              </Badge>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
                The Aanant Family Legacy
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                Four generations of sustainable living expertise, combining traditional wisdom with modern innovation
              </p>
            </div>

            {/* Family Photo */}
            <div className="mb-16">
              <Card className="overflow-hidden">
                <div className="relative h-96">
                  <img
                    src={familyLegacy.familyPhoto}
                    alt="The Aanant Family"
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
                  <div className="absolute bottom-0 left-0 right-0 p-8 text-white">
                    <h3 className="text-3xl font-bold mb-2">Four Generations of Sustainable Living</h3>
                    <p className="text-xl">Great-grandparents' wisdom + Modern sustainable technology = Complete family commitment to organic living</p>
                  </div>
                </div>
              </Card>
            </div>

            {/* Peter Singh */}
            <div className="mb-16">
              <Card className="overflow-hidden shadow-2xl">
                <div className="grid lg:grid-cols-2 gap-0">
                  <div className="relative">
                    <img
                      src={familyLegacy.peter.image}
                      alt="Dr. Peter Singh"
                      className="w-full h-full object-cover min-h-[500px]"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
                    <div className="absolute bottom-6 left-6 text-white">
                      <Badge className="bg-amber-700 text-white mb-2">
                        <Award className="w-4 h-4 mr-2" />
                        Founder & Chief Scientist
                      </Badge>
                    </div>
                  </div>

                  <div className="p-8 lg:p-12">
                    <div className="mb-6">
                      <h3 className="text-3xl font-bold text-gray-900 mb-2">
                        Peter Singh
                      </h3>
                      <p className="text-xl text-amber-700 font-medium mb-2">
                        Born 1945, Punjab Organic Farm
                      </p>
                      <div className="flex items-center gap-4 text-sm text-gray-600">
                        <div className="flex items-center gap-1">
                          <BookOpen className="w-4 h-4" />
                          <span>Lawrence School Sanawar & St. Stephens College</span>
                        </div>
                      </div>
                    </div>

                    <div className="mb-8">
                      <h4 className="text-xl font-bold text-gray-900 mb-4">Career Journey</h4>
                      <div className="space-y-3">
                        {familyLegacy.peter.career.map((item, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <CheckCircle className="w-5 h-5 text-amber-600 mt-0.5" />
                            <span className="text-gray-700">{item}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="mb-8">
                      <h4 className="text-xl font-bold text-gray-900 mb-4">Government Recognition</h4>
                      <div className="space-y-3">
                        {familyLegacy.peter.recognition.map((item, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <Trophy className="w-5 h-5 text-yellow-600 mt-0.5" />
                            <span className="text-gray-700">{item}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="bg-amber-50 p-6 rounded-lg border-l-4 border-amber-600">
                      <Quote className="w-8 h-8 text-amber-600 mb-3" />
                      <blockquote className="text-lg italic text-amber-800 mb-3">
                        "The land called me back. I chose farming over academia because I believed sustainable agriculture 
                        could transform not just the environment, but human health and community prosperity."
                      </blockquote>
                      <cite className="text-amber-700 font-medium">— Peter Singh</cite>
                    </div>
                  </div>
                </div>
              </Card>
            </div>

            {/* Neeno Kaur */}
            <div className="mb-16">
              <Card className="overflow-hidden shadow-2xl">
                <div className="grid lg:grid-cols-2 gap-0">
                  <div className="p-8 lg:p-12 order-2 lg:order-1">
                    <div className="mb-6">
                      <h3 className="text-3xl font-bold text-gray-900 mb-2">
                        Sarparveen (Neeno) Kaur
                      </h3>
                      <p className="text-xl text-blue-700 font-medium mb-4">
                        Born 1955
                      </p>
                      <div className="flex items-center gap-4 text-sm text-gray-600">
                        <div className="flex items-center gap-1">
                          <Award className="w-4 h-4" />
                          <span>All India President, FICCI Ladies Organization (1997-1998)</span>
                        </div>
                      </div>
                    </div>

                    <div className="mb-8">
                      <h4 className="text-xl font-bold text-gray-900 mb-4">Remarkable Journey</h4>
                      <div className="space-y-3">
                        {familyLegacy.neeno.achievements.map((achievement, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <CheckCircle className="w-5 h-5 text-blue-600 mt-0.5" />
                            <span className="text-gray-700">{achievement}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="mb-8">
                      <h4 className="text-xl font-bold text-gray-900 mb-4">Current Role</h4>
                      <div className="flex items-start gap-3">
                        <Leaf className="w-5 h-5 text-green-600 mt-0.5" />
                        <span className="text-gray-700">{familyLegacy.neeno.currentRole}</span>
                      </div>
                    </div>

                    <div className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-600">
                      <Quote className="w-8 h-8 text-blue-600 mb-3" />
                      <blockquote className="text-lg italic text-blue-800 mb-3">
                        "True health isn't just the absence of disease—it's the presence of vitality, purpose, 
                        and harmony with our environment. When we heal the earth, we heal ourselves."
                      </blockquote>
                      <cite className="text-blue-700 font-medium">— Neeno Kaur</cite>
                    </div>
                  </div>

                  <div className="relative order-1 lg:order-2">
                    <img
                      src={familyLegacy.neeno.image}
                      alt="Neeno Kaur"
                      className="w-full h-full object-cover min-h-[500px]"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
                    <div className="absolute bottom-6 right-6 text-white">
                      <Badge className="bg-blue-700 text-white mb-2">
                        <Heart className="w-4 h-4 mr-2" />
                        Co-Founder & Health Advocate
                      </Badge>
                    </div>
                  </div>
                </div>
              </Card>
            </div>

            {/* Next Generation */}
            <div className="mb-16">
              <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">
                The Next Generation
              </h3>
              <div className="grid md:grid-cols-2 gap-8">
                {familyLegacy.nextGen.map((person, index) => (
                  <Card key={index} className="overflow-hidden hover:shadow-lg transition-all duration-300">
                    <div className="grid sm:grid-cols-3 gap-0">
                      <div className="relative">
                        <img
                          src={person.image}
                          alt={person.name}
                          className="w-full h-full object-cover min-h-[200px]"
                        />
                      </div>
                      <div className="sm:col-span-2 p-6">
                        <h4 className="text-xl font-bold text-gray-900 mb-2">{person.name}</h4>
                        <p className="text-purple-700 font-medium mb-4">{person.relation}</p>
                        <div className="space-y-2 mb-4">
                          <div className="flex items-start gap-2">
                            <BookOpen className="w-4 h-4 text-blue-600 mt-1" />
                            <span className="text-gray-700">{person.education}</span>
                          </div>
                          <div className="flex items-start gap-2">
                            <Briefcase className="w-4 h-4 text-green-600 mt-1" />
                            <span className="text-gray-700">{person.role}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            </div>

            {/* Four Generations Living Together */}
            <Card className="p-8 bg-gradient-to-r from-amber-50 to-green-50 border-amber-200 mb-16">
              <CardContent className="p-0">
                <div className="text-center mb-8">
                  <Home className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">
                    Four Generations Living Together
                  </h3>
                </div>
                <div className="grid md:grid-cols-3 gap-8">
                  <div className="text-center">
                    <Flower className="w-12 h-12 text-amber-600 mx-auto mb-4" />
                    <h4 className="font-bold text-gray-900 mb-2">Great-Grandparents' Wisdom</h4>
                    <p className="text-gray-700">
                      Traditional agricultural knowledge and sustainable living practices passed down through generations
                    </p>
                  </div>
                  <div className="text-center">
                    <Zap className="w-12 h-12 text-blue-600 mx-auto mb-4" />
                    <h4 className="font-bold text-gray-900 mb-2">Modern Sustainable Technology</h4>
                    <p className="text-gray-700">
                      Cutting-edge scientific approaches and innovative systems for maximum efficiency
                    </p>
                  </div>
                  <div className="text-center">
                    <Heart className="w-12 h-12 text-green-600 mx-auto mb-4" />
                    <h4 className="font-bold text-gray-900 mb-2">Complete Family Commitment</h4>
                    <p className="text-gray-700">
                      A unified vision of sustainable living that spans four generations under one roof
                    </p>
                  </div>
                </div>
                <div className="mt-8 text-center">
                  <p className="text-lg text-gray-700 italic">
                    "Our greatest strength is the harmony of traditional wisdom and modern innovation that comes from 
                    four generations living and working together with a shared purpose."
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Media Coverage Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <Badge variant="outline" className="mb-4 px-4 py-2 text-blue-700 border-blue-200">
                <Globe className="w-4 h-4 mr-2" />
                Media Recognition
              </Badge>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
                International Media Coverage &{' '}
                <span className="text-green-700">Government Recognition</span>
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                Our pioneering work has gained recognition from leading media outlets worldwide and 
                received official acknowledgment from government institutions.
              </p>
            </div>

            {/* Media Coverage Grid */}
            <div className="mb-16">
              <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">
                Featured in Leading Publications & Broadcasts
              </h3>
              
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
                {mediaCoverage.international.map((media, index) => {
                  const Icon = getMediaIcon(media.type);
                  return (
                    <Card key={index} className="hover:shadow-lg transition-all duration-300 group">
                      <CardContent className="p-6">
                        <div className="flex items-start gap-4 mb-4">
                          <div className="w-12 h-12 bg-blue-50 rounded-lg flex items-center justify-center">
                            <Icon className="w-6 h-6 text-blue-600" />
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <h4 className="font-bold text-gray-900">{media.outlet}</h4>
                              <Badge variant="outline" className="text-xs">
                                {media.country}
                              </Badge>
                            </div>
                            <p className="text-sm text-gray-600 mb-2">{media.type} • {media.date}</p>
                          </div>
                        </div>
                        
                        <h5 className="font-semibold text-gray-900 mb-2 leading-tight">
                          {media.headline}
                        </h5>
                        <p className="text-sm text-gray-600 mb-4 leading-relaxed">
                          {media.description}
                        </p>
                        
                        <Button 
                          variant="outline" 
                          size="sm" 
                          className="w-full group-hover:bg-blue-50 group-hover:border-blue-300"
                        >
                          <ExternalLink className="w-4 h-4 mr-2" />
                          Read Coverage
                        </Button>
                      </CardContent>
                    </Card>
                  );
                })}
              </div>

              {/* Media Quotes */}
              <div className="bg-gray-50 p-8 rounded-lg">
                <h4 className="text-xl font-bold text-gray-900 mb-6 text-center">
                  What Media Leaders Are Saying
                </h4>
                <div className="grid md:grid-cols-3 gap-6">
                  {mediaQuotes.map((quote, index) => (
                    <div key={index} className="bg-white p-6 rounded-lg border">
                      <Quote className="w-6 h-6 text-blue-600 mb-3" />
                      <blockquote className="text-gray-700 italic mb-4">
                        "{quote.quote}"
                      </blockquote>
                      <div className="text-sm">
                        <p className="font-semibold text-gray-900">{quote.source}</p>
                        <p className="text-gray-600">{quote.journalist}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Government Recognition */}
            <div>
              <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">
                Government Recognition & Awards
              </h3>
              
              <div className="grid md:grid-cols-2 gap-6">
                {governmentRecognition.map((recognition, index) => {
                  const Icon = recognition.icon;
                  return (
                    <Card key={index} className={`hover:shadow-lg transition-all duration-300 ${getColorClasses(recognition.color)}`}>
                      <CardContent className="p-6">
                        <div className="flex items-start gap-4">
                          <div className={`w-12 h-12 rounded-lg flex items-center justify-center ${getColorClasses(recognition.color)}`}>
                            <Icon className="w-6 h-6" />
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <Badge className="bg-gray-900 text-white">
                                {recognition.year}
                              </Badge>
                              <Badge variant="outline" className="text-xs">
                                {recognition.authority}
                              </Badge>
                            </div>
                            <h4 className="font-bold text-gray-900 mb-2 leading-tight">
                              {recognition.title}
                            </h4>
                            <p className="text-sm text-gray-700 leading-relaxed">
                              {recognition.description}
                            </p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            </div>

            {/* Recognition Summary */}
            <div className="mt-12">
              <Card className="p-8 bg-gradient-to-r from-yellow-50 to-orange-50 border-yellow-200">
                <div className="text-center">
                  <Trophy className="w-12 h-12 text-yellow-600 mx-auto mb-4" />
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">
                    Recognition Timeline
                  </h3>
                  <p className="text-gray-700 mb-6 max-w-3xl mx-auto">
                    From pioneering beekeeping innovations in 1988 to becoming a resource person for the Ministry of Agriculture, 
                    our founders have consistently received recognition for their contributions to sustainable agriculture and 
                    environmental innovation.
                  </p>
                  <div className="grid md:grid-cols-4 gap-6">
                    <div className="text-center">
                      <div className="text-3xl font-bold text-yellow-700">36 Years</div>
                      <p className="text-sm text-gray-600">Government Recognition</p>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-orange-700">9 Outlets</div>
                      <p className="text-sm text-gray-600">International Media</p>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-green-700">3 Countries</div>
                      <p className="text-sm text-gray-600">Global Coverage</p>
                    </div>
                    <div className="text-center">
                      <div className="text-3xl font-bold text-blue-700">4 Awards</div>
                      <p className="text-sm text-gray-600">Government Honors</p>
                    </div>
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Timeline Section */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
                26 Years of Innovation & Impact
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                From personal crisis to global impact—the journey that transformed two lives 
                and sparked a movement affecting hundreds of families.
              </p>
            </div>

            {/* Interactive Timeline */}
            <div className="relative">
              {/* Timeline Line */}
              <div className="absolute left-1/2 transform -translate-x-1/2 w-1 h-full bg-gradient-to-b from-green-200 via-blue-200 to-purple-200 hidden md:block"></div>

              <div className="space-y-12">
                {milestones.map((milestone, index) => {
                  const Icon = milestone.icon;
                  const isActive = index === activeTimeline;
                  const isEven = index % 2 === 0;

                  return (
                    <div
                      key={index}
                      className={`relative transition-all duration-1000 ${
                        isActive ? 'scale-105' : ''
                      }`}
                    >
                      {/* Timeline Point */}
                      <div className="absolute left-1/2 transform -translate-x-1/2 w-12 h-12 bg-white border-4 border-green-400 rounded-full flex items-center justify-center z-10 hidden md:flex">
                        <Icon className="w-6 h-6 text-green-600" />
                      </div>

                      {/* Content Card */}
                      <div className={`grid md:grid-cols-2 gap-8 items-center ${isEven ? '' : 'md:direction-rtl'}`}>
                        <div className={`${isEven ? 'md:text-right md:pr-16' : 'md:text-left md:pl-16'}`}>
                          <Card className={`p-6 ${isActive ? 'ring-2 ring-green-400 bg-green-50' : 'hover:shadow-lg'} transition-all duration-300`}>
                            <CardContent className="p-0">
                              <div className="flex items-center gap-3 mb-4 md:hidden">
                                <Icon className="w-6 h-6 text-green-600" />
                                <Badge variant="secondary" className="text-lg font-bold">
                                  {milestone.year}
                                </Badge>
                              </div>
                              <Badge variant="secondary" className="text-lg font-bold mb-4 hidden md:inline-block">
                                {milestone.year}
                              </Badge>
                              <h3 className="text-xl font-bold mb-3 text-gray-900">
                                {milestone.title}
                              </h3>
                              <p className="text-gray-700 mb-4 leading-relaxed">
                                {milestone.description}
                              </p>
                              <Badge variant="outline" className="text-green-700 border-green-200">
                                {milestone.impact}
                              </Badge>
                            </CardContent>
                          </Card>
                        </div>

                        <div className={`${isEven ? 'md:pl-16' : 'md:pr-16'}`}>
                          <div className="text-center p-6 bg-gray-50 rounded-lg">
                            <div className="text-4xl font-bold text-green-700 mb-2">
                              {milestone.year}
                            </div>
                            <p className="text-gray-600">{milestone.impact}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Impact Metrics */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
                Measurable Impact & Recognition
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                Our commitment to excellence is reflected in the tangible results we've achieved 
                and the recognition we've received from the agricultural and scientific communities.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
              {achievements.map((achievement, index) => {
                const Icon = achievement.icon;
                return (
                  <Card key={index} className="text-center p-6 hover:shadow-xl transition-all duration-300">
                    <div className={`w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center ${getColorClasses(achievement.color)}`}>
                      <Icon className="w-8 h-8" />
                    </div>
                    <div className="text-3xl font-bold text-gray-900 mb-2">
                      {achievement.metric}
                    </div>
                    <h4 className="font-semibold text-gray-900 mb-2">{achievement.label}</h4>
                    <p className="text-sm text-gray-600">{achievement.description}</p>
                  </Card>
                );
              })}
            </div>

            {/* Awards & Recognition */}
            <Card className="p-8 bg-gradient-to-r from-yellow-50 to-orange-50 border-yellow-200">
              <div className="text-center mb-8">
                <Award className="w-12 h-12 text-yellow-600 mx-auto mb-4" />
                <h3 className="text-2xl font-bold text-gray-900 mb-4">
                  Awards & Recognition
                </h3>
              </div>
              <div className="grid md:grid-cols-3 gap-6">
                <div className="text-center p-4 bg-white rounded-lg border">
                  <div className="text-lg font-bold text-yellow-700 mb-2">Delhi Pollution Control Committee</div>
                  <p className="text-sm text-gray-600">
                    Recognized as innovative air quality improvement solution (2022)
                  </p>
                </div>
                <div className="text-center p-4 bg-white rounded-lg border">
                  <div className="text-lg font-bold text-green-700 mb-2">Ministry of Agriculture</div>
                  <p className="text-sm text-gray-600">
                    Featured in sustainable urban farming initiatives (2023)
                  </p>
                </div>
                <div className="text-center p-4 bg-white rounded-lg border">
                  <div className="text-lg font-bold text-blue-700 mb-2">WHO Collaboration</div>
                  <p className="text-sm text-gray-600">
                    Environmental health research partnership (2024)
                  </p>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
                What Industry Leaders Say
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                Recognition from peers, colleagues, and the communities we serve validates 
                our commitment to excellence and impact.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              {testimonials.map((testimonial, index) => (
                <Card key={index} className="hover:shadow-xl transition-all duration-300">
                  <CardContent className="p-6">
                    <div className="flex items-center mb-4">
                      <img
                        src={testimonial.image}
                        alt={testimonial.name}
                        className="w-12 h-12 rounded-full object-cover mr-4"
                      />
                      <div>
                        <h4 className="font-semibold text-gray-900">{testimonial.name}</h4>
                        <p className="text-sm text-gray-600">{testimonial.role}</p>
                      </div>
                    </div>
                    <Quote className="w-6 h-6 text-green-600 mb-3" />
                    <blockquote className="text-gray-700 italic mb-4">
                      "{testimonial.quote}"
                    </blockquote>
                    <div className="flex items-center">
                      {[...Array(5)].map((_, i) => (
                        <Star key={i} className="w-4 h-4 text-yellow-500 fill-current" />
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-20 bg-gradient-to-r from-green-600 to-blue-600 text-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">
              Ready to Join Our Mission?
            </h2>
            <p className="text-xl mb-8 text-green-100">
              Whether you're interested in our training programs, consultation services, or partnership opportunities, 
              we're here to help you create sustainable change in your community.
            </p>
            
            <div className="grid md:grid-cols-3 gap-6 mb-12">
              <Card className="p-6 bg-white/10 backdrop-blur-sm border-white/20 text-white">
                <BookOpen className="w-8 h-8 mx-auto mb-4" />
                <h3 className="text-xl font-bold mb-2">Training Programs</h3>
                <p className="text-green-100 mb-4">
                  Comprehensive courses designed to transform your understanding of sustainable agriculture.
                </p>
                <Button variant="outline" className="border-white text-white hover:bg-white hover:text-green-700">
                  <ArrowRight className="w-4 h-4 mr-2" />
                  Explore Courses
                </Button>
              </Card>

              <Card className="p-6 bg-white/10 backdrop-blur-sm border-white/20 text-white">
                <MessageCircle className="w-8 h-8 mx-auto mb-4" />
                <h3 className="text-xl font-bold mb-2">Consultation Services</h3>
                <p className="text-green-100 mb-4">
                  Personalized guidance for implementing sustainable solutions in your space.
                </p>
                <Button variant="outline" className="border-white text-white hover:bg-white hover:text-blue-700">
                  <ArrowRight className="w-4 h-4 mr-2" />
                  Book Consultation
                </Button>
              </Card>

              <Card className="p-6 bg-white/10 backdrop-blur-sm border-white/20 text-white">
                <Handshake className="w-8 h-8 mx-auto mb-4" />
                <h3 className="text-xl font-bold mb-2">Partnership Opportunities</h3>
                <p className="text-green-100 mb-4">
                  Collaborate with us to scale sustainable agriculture solutions globally.
                </p>
                <Button variant="outline" className="border-white text-white hover:bg-white hover:text-purple-700">
                  <ArrowRight className="w-4 h-4 mr-2" />
                  Partner With Us
                </Button>
              </Card>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="bg-white text-green-700 hover:bg-gray-100">
                <Phone className="w-5 h-5 mr-2" />
                Call +91 98765 43210
              </Button>
              <Button size="lg" variant="outline" className="border-white text-white hover:bg-white hover:text-green-700">
                <Mail className="w-5 h-5 mr-2" />
                Email Us
              </Button>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}